apiVersion: v1
kind: ReplicationController
metadata:
  name: elixir-io

spec:
  replicas: 2
  selector:
    app: elixir-io

  template: 
    metadata:
      labels: 
        app: elixir-io
    spec: 
      containers:
      - name: elixir-io
        image: princeigwe/elixir.io:latest
        envFrom:
          - secretRef:
              name: elixir-io-secret
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
